#!/usr/bin/env python3
"""gen_pceapi.py — Generate P/ECE kernel API stubs from vector.h.

Usage:
    python3 gen_pceapi.py tools/crt/vector.h -o build/pceapi_stubs.s

Reads KSNO_* and KSNO2_* definitions from vector.h and emits LLVM assembler
source with expanded xld.w sequences (S1C33 ext + ld.w).

Stub templates (from sdk/lib/src/lib1.s and lib2.s):

  KSNO_*  (lib1): Load kernel service function pointer from the kernel service
  table via R8 (GP), then jump to it.

      xld.w %r9, [%r8 + (0x20 + no*4)]   ; load service pointer
      jp %r9

  KSNO2_* (lib2): Load service vector number into R9, then invoke the kernel
  via software interrupt.

      xld.w %r9, (0x20 + no*4)            ; load service number
      int 1

xld.w expansion (single ext, valid for values < 8192):
  xld.w %rd, [%rb + offset]  ->  ext offset    + ld.w %rd, [%rb]
  xld.w %rd, imm             ->  ext (imm>>6)  + ld.w %rd, sign6(imm)

All KSNO offsets (0x20..0x208) and KSNO2 values (0x320..0x330) fit in
13 bits, so a single ext instruction suffices.

Note: jp %r9 is used (not jp.d %r9). The hardware bug documented in errata.md
makes jp.d %rb unreliable when DMA is active.
"""

import re
import sys
import argparse


def sign6(v: int) -> int:
    """Return the 6-bit signed interpretation of the low 6 bits of v."""
    b = v & 0x3F
    return b if b < 32 else b - 64


def expand_xld_regind(rd: str, rb: str, offset: int) -> list:
    """xld.w %rd, [%rb + offset]  ->  ext offset + ld.w %rd, [%rb]"""
    return [
        f"\text\t{offset:#x}",
        f"\tld.w\t{rd}, [{rb}]",
    ]


def expand_xld_imm(rd: str, value: int) -> list:
    """xld.w %rd, value  ->  ext (value>>6) + ld.w %rd, sign6(value)

    Valid for value < 8192 (13-bit range).  All KSNO2 values satisfy this.
    """
    ext_mid = (value >> 6) & 0x1FFF
    base = sign6(value)
    return [
        f"\text\t{ext_mid:#x}",
        f"\tld.w\t{rd}, {base}",
    ]


def parse_vector_h(path: str) -> tuple:
    """Parse vector.h and return (ksno, ksno2) dicts of name -> number."""
    ksno = {}
    ksno2 = {}
    pat1 = re.compile(r'#define\s+KSNO_(\w+)\s+(\d+)')
    pat2 = re.compile(r'#define\s+KSNO2_(\w+)\s+(\d+)')
    with open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            m = pat1.search(line)
            if m:
                ksno[m.group(1)] = int(m.group(2))
                continue
            m = pat2.search(line)
            if m:
                ksno2[m.group(1)] = int(m.group(2))
    return ksno, ksno2


def make_lib1_stub(name: str, no: int) -> str:
    """lib1: kernel service via R8-based table.

    R8 (GP) points to the kernel service table base.
    The service pointer is at [R8 + 0x20 + no*4].
    Load the pointer into R9 via ext+ld.w, then jump with jp %r9.

    jp (not jp.d) per errata: jp.d %rb is unreliable when DMA is active.
    """
    offset = 0x20 + no * 4
    insns = expand_xld_regind('%r9', '%r8', offset)
    insns.append('\tjp\t%r9')
    body = '\n'.join(insns)
    return (
        f"\t.global\tpce{name}\n"
        f"pce{name}:\t\t\t\t; KSNO_{name} = {no}, offset = {offset:#x}\n"
        f"{body}\n"
    )


def make_lib2_stub(name: str, no: int) -> str:
    """lib2: synchronisation service via software interrupt.

    Load the service vector number (0x20 + no*4) into R9 via ext+ld.w,
    then invoke the kernel with 'int 1'.
    """
    value = 0x20 + no * 4
    insns = expand_xld_imm('%r9', value)
    insns.append('\tint\t1')
    body = '\n'.join(insns)
    return (
        f"\t.global\tpce{name}\n"
        f"pce{name}:\t\t\t\t; KSNO2_{name} = {no}, value = {value:#x}\n"
        f"{body}\n"
    )


STUB_HEADER = """\
// Auto-generated by gen_pceapi.py -- DO NOT EDIT
// Source: tools/crt/vector.h
//
// P/ECE kernel API stub for S1C33 (LLVM assembler format).
//
\t.text
"""


def write_stub(text: str, path: str) -> None:
    with open(path, 'w') as f:
        f.write(text)


def main() -> None:
    ap = argparse.ArgumentParser(
        description='Generate P/ECE kernel API stubs from vector.h')
    ap.add_argument('vector_h', help='Path to vector.h (with KSNO_* defines)')
    ap.add_argument('-o', '--output', default='-',
                    help='Output .s file (default: stdout); ignored with --split-dir')
    ap.add_argument('--split-dir', metavar='DIR',
                    help='Write one .s file per stub into DIR (pce<Name>.s)')
    args = ap.parse_args()

    ksno, ksno2 = parse_vector_h(args.vector_h)
    if not ksno and not ksno2:
        print(f"ERROR: no KSNO_* definitions found in {args.vector_h}",
              file=sys.stderr)
        sys.exit(1)

    if args.split_dir:
        import os
        os.makedirs(args.split_dir, exist_ok=True)
        count = 0
        for name, no in sorted(ksno.items(), key=lambda x: x[1]):
            stub = STUB_HEADER + make_lib1_stub(name, no)
            write_stub(stub, os.path.join(args.split_dir, f'pce{name}.s'))
            count += 1
        for name, no in sorted(ksno2.items(), key=lambda x: x[1]):
            stub = STUB_HEADER + make_lib2_stub(name, no)
            write_stub(stub, os.path.join(args.split_dir, f'pce{name}.s'))
            count += 1
        print(
            f"gen_pceapi: {len(ksno)} lib1 + {len(ksno2)} lib2 = "
            f"{count} stubs -> {args.split_dir}/",
            file=sys.stderr,
        )
        return

    out = []
    out.append('// Auto-generated by gen_pceapi.py -- DO NOT EDIT\n')
    out.append('// Source: tools/crt/vector.h\n')
    out.append('//\n')
    out.append('// P/ECE kernel API stubs for S1C33 (LLVM assembler format).\n')
    out.append('//\n')
    out.append('// lib1 stubs (KSNO_*): load service pointer from [R8 + offset], jp R9.\n')
    out.append('//   R8 (GP) = kernel service table base (KSVECTORTOP = 0x20).\n')
    out.append('//\n')
    out.append('// lib2 stubs (KSNO2_*): load service number into R9, int 1.\n')
    out.append('//   The kernel dispatches via the software interrupt handler.\n')
    out.append('//\n')
    out.append('\t.text\n')
    out.append('\n')

    out.append('// --- lib1: Normal kernel services (KSNO_*) ---\n\n')
    for name, no in sorted(ksno.items(), key=lambda x: x[1]):
        out.append(make_lib1_stub(name, no))
        out.append('\n')

    out.append('// --- lib2: Synchronisation services (KSNO2_*) ---\n\n')
    for name, no in sorted(ksno2.items(), key=lambda x: x[1]):
        out.append(make_lib2_stub(name, no))
        out.append('\n')

    text = ''.join(out)

    if args.output == '-':
        sys.stdout.write(text)
    else:
        with open(args.output, 'w') as f:
            f.write(text)

    print(
        f"gen_pceapi: {len(ksno)} lib1 + {len(ksno2)} lib2 = "
        f"{len(ksno) + len(ksno2)} stubs -> {args.output}",
        file=sys.stderr,
    )


if __name__ == '__main__':
    main()
