// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: 01.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_01_bin
pmd2s_01_bin:
	.incbin		"01.pmd"
	.global		pmd2s_01_bin_end
pmd2s_01_bin_end:
