// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: eew.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_eew_bin
pmd2s_eew_bin:
	.incbin		"eew.pmd"
	.global		pmd2s_eew_bin_end
pmd2s_eew_bin_end:
