// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: eew0.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_eew0_bin
pmd2s_eew0_bin:
	.incbin		"eew0.pmd"
	.global		pmd2s_eew0_bin_end
pmd2s_eew0_bin_end:
