// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: eew1.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_eew1_bin
pmd2s_eew1_bin:
	.incbin		"eew1.pmd"
	.global		pmd2s_eew1_bin_end
pmd2s_eew1_bin_end:
