// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: eew2.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_eew2_bin
pmd2s_eew2_bin:
	.incbin		"eew2.pmd"
	.global		pmd2s_eew2_bin_end
pmd2s_eew2_bin_end:
