// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: eew3.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_eew3_bin
pmd2s_eew3_bin:
	.incbin		"eew3.pmd"
	.global		pmd2s_eew3_bin_end
pmd2s_eew3_bin_end:
