// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: eew4.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_eew4_bin
pmd2s_eew4_bin:
	.incbin		"eew4.pmd"
	.global		pmd2s_eew4_bin_end
pmd2s_eew4_bin_end:
