// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: eew5.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_eew5_bin
pmd2s_eew5_bin:
	.incbin		"eew5.pmd"
	.global		pmd2s_eew5_bin_end
pmd2s_eew5_bin_end:
