// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: eewA.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_eewA_bin
pmd2s_eewA_bin:
	.incbin		"eewA.pmd"
	.global		pmd2s_eewA_bin_end
pmd2s_eewA_bin_end:
