// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: neruneru.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_neruneru_bin
pmd2s_neruneru_bin:
	.incbin		"neruneru.pmd"
	.global		pmd2s_neruneru_bin_end
pmd2s_neruneru_bin_end:
