// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: neruneru2.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_neruneru2_bin
pmd2s_neruneru2_bin:
	.incbin		"neruneru2.pmd"
	.global		pmd2s_neruneru2_bin_end
pmd2s_neruneru2_bin_end:
