#!/bin/sh

# this script gathers symbol from .s files, then generates a .h file with extern declarations for those symbols
# the .s files are expected to be generated by pmd2s.sh, and the .h file is expected to be included in the final binary

cat <<__EOF__
// This file is auto-generated by pmd2h.sh. Do not edit manually.
#ifndef PMD_DATA_H
#define PMD_DATA_H

__EOF__

grep "^pmd2s_.*.bin:" *.s | sed -E 's/.*(pmd2s_.*.bin).*/extern const unsigned char \1[];/'

cat <<__EOF__

#endif // PMD_DATA_H
__EOF__

