#!/bin/sh

# this script generates .s files by ".incbin"-ing the .pmd file specified as argument,
# which can then be linked into the final binary


SRC=$1

if [ -z "$SRC" ]; then
    echo "Usage: $0 <file.pmd>"
    exit 1
fi

BASENAME=$(basename "$SRC" .pmd)

cat <<__EOF__
// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: ${SRC}
	.section	.rodata
	.balign		4
	.global		pmd2s_${BASENAME}_bin
pmd2s_${BASENAME}_bin:
	.incbin		"${SRC}"
	.global		pmd2s_${BASENAME}_bin_end
pmd2s_${BASENAME}_bin_end:
__EOF__
