// This file is auto-generated by pmd2h.sh. Do not edit manually.
#ifndef PMD_DATA_H
#define PMD_DATA_H

extern const unsigned char pmd2s_01_bin[];
extern const unsigned char pmd2s_eew_bin[];
extern const unsigned char pmd2s_eew0_bin[];
extern const unsigned char pmd2s_eew1_bin[];
extern const unsigned char pmd2s_eew2_bin[];
extern const unsigned char pmd2s_eew3_bin[];
extern const unsigned char pmd2s_eew4_bin[];
extern const unsigned char pmd2s_eew5_bin[];
extern const unsigned char pmd2s_eewA_bin[];
extern const unsigned char pmd2s_neruneru_bin[];
extern const unsigned char pmd2s_neruneru2_bin[];
extern const unsigned char pmd2s_yzs007_16_bin[];
extern const unsigned char pmd2s_yzs010_opna_bin[];

#endif // PMD_DATA_H
