// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: yzs007_16.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_yzs007_16_bin
pmd2s_yzs007_16_bin:
	.incbin		"yzs007_16.pmd"
	.global		pmd2s_yzs007_16_bin_end
pmd2s_yzs007_16_bin_end:
