// This file is auto-generated by pmd2s.sh. Do not edit manually.
// generated from: yzs010_opna.pmd
	.section	.rodata
	.balign		4
	.global		pmd2s_yzs010_opna_bin
pmd2s_yzs010_opna_bin:
	.incbin		"yzs010_opna.pmd"
	.global		pmd2s_yzs010_opna_bin_end
pmd2s_yzs010_opna_bin_end:
